// Last Updated: v1.21.0.24-preview

export enum DeathAttackMessage {
  anvil = "death.attack.anvil",
  arrow = "death.attack.arrow",
  arrowItem = "death.attack.arrow.item",
  bullet = "death.attack.bullet",
  cactus = "death.attack.cactus",
  cactusPlayer = "death.attack.cactus.player",
  drown = "death.attack.drown",
  drownPlayer = "death.attack.drown.player",
  explosion = "death.attack.explosion",
  explosionByBed = "death.attack.explosion.by.bed",
  explosionPlayer = "death.attack.explosion.player",
  fall = "death.attack.fall",
  fallingBlock = "death.attack.fallingBlock",
  fireball = "death.attack.fireball",
  fireballItem = "death.attack.fireball.item",
  fireworks = "death.attack.fireworks",
  flyIntoWall = "death.attack.flyIntoWall",
  generic = "death.attack.generic",
  indirectMagic = "death.attack.indirectMagic",
  indirectMagicItem = "death.attack.indirectMagic.item",
  inFire = "death.attack.inFire",
  inFirePlayer = "death.attack.inFire.player",
  inWall = "death.attack.inWall",
  lava = "death.attack.lava",
  lavaPlayer = "death.attack.lava.player",
  lightningBolt = "death.attack.lightningBolt",
  magic = "death.attack.magic",
  magma = "death.attack.magma",
  magmaPlayer = "death.attack.magma.player",
  mob = "death.attack.mob",
  mobItem = "death.attack.mob.item",
  onFire = "death.attack.onFire",
  onFirePlayer = "death.attack.onFire.player",
  outOfWorld = "death.attack.outOfWorld",
  player = "death.attack.player",
  playerItem = "death.attack.player.item",
  spit = "death.attack.spit",
  starve = "death.attack.starve",
  sweetBerry = "death.attack.sweetBerry",
  thorns = "death.attack.thorns",
  thrown = "death.attack.thrown",
  thrownItem = "death.attack.thrown.item",
  trident = "death.attack.trident",
  wither = "death.attack.wither",
  freeze = "death.attack.freeze",
  sonicBoom = "death.attack.sonicBoom",
  sonicBoomPlayer = "death.attack.sonicBoom.player",
  stalactite = "death.attack.stalactite",
  stalagmite = "death.attack.stalagmite",
}

export enum DeathFellMessage {
  accidentGeneric = "death.fell.accident.generic",
  accidentLadder = "death.fell.accident.ladder",
  accidentVines = "death.fell.accident.vines",
  accidentWater = "death.fell.accident.water",
  assist = "death.fell.assist",
  assistItem = "death.fell.assist.item",
  finish = "death.fell.finish",
  finishItem = "death.fell.finish.item",
  killer = "death.fell.killer",
}
